### ISSUE TITLE
Chapter 1 - Matchgame

### ISSUE THREAD

**Issue by GazG-commits** [head-first-csharp/fourth-edition#44]
Having added the emoji to the grid with xaml and input the C# code as instructed I get the following error:-

System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='The invocation of the constructor on type 'MatchGame.MainWindow' that matches the specified binding constraints threw an exception.' Line number '6' and line position '9'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at MatchGame.App.Main()

  This exception was originally thrown at this call stack:
    [External Code]
    MatchGame.MainWindow.SetUpGame() in MainWindow.xaml.cs
    MatchGame.MainWindow.MainWindow() in MainWindow.xaml.cs

Inner Exception 1:
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Arg_ParamName_Name

*** I am using VS Community 2022 - Has something changed since the 2019 edition that would cause this error?

**Comment by andrewstellman** [comment]
Looks like you got the 'Index was out of range' error – most of the time it's because there's an extra TextBlock. Here's an explanation, with tips for fixing it: https://github.com/head-first-csharp/fourth-edition#systemargumentoutofrangeexception-index-was-out-of-range

Can you have a look at that and see if it helps you fix the issue?

**Comment by GazG-commits** [comment]
Thanks for the pointer (Heads up!) Andrew.
I missed the crucial statement on page 19 of the exercise where it states "But we need **16 TextBlocks** to show all of the animals to match. "
I obviously got carried away with the copying and pasting of my code in XAML and carried on through the fifth row!
The issue is now fixed.

Thanks for your help Andrew (I am honored that one of the co-authors replied to my question).
I am amazed that such a busy person as yourself has the time to answer Github's comments.
Kudos to the great Andrew!

** side note - I love your books on C#, this is the third one I have purchased. Sadly, I was too busy with work when I had the two earlier editions to get enough practice—thoroughly enjoying this experience, now that I am semi-retired.

Kind Regards

Gary (aka Gaz)

**Comment by andrewstellman** [comment]
My pleasure—so glad to help! It's super important to both me and Jenny that all of our readers get the most out of our books. And it's so cool that you kept with our book. Honestly, I think this one was worth the wait. We learned so much from our readers over the year, and I think we made a lot of improvements in the 4th edition. I hope you enjoy it!
